tasks:
  - name: R3_A
    events:
      - type: gate
        label: Gate-1
        location: [ [ 4.69, 3.035 ], [ 1.79, 3.035 ] ]
      - type: gate
        label: Gate-2
        location: [ [ 4.69, 15.05 ], [ 1.79, 15.05 ] ]
    doorTargetPoints: [ [ 4.302, 10.958, 1.118 ], [ 4.337, 10.946, 0.876 ], [ 4.344, 9.953, 1.066 ] ]
